name: flutter_money_utils
description: The utils for clear amount from trash.
version: 1.0.1
homepage: https://github.com/Witerius/FlutterMoneyUtils

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.witerius.flutter_money_utils.flutter_money_utils
    iosBundleIdentifier: com.witerius.fluttermoneyutils.flutterMoneyUtils
